version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  
  node:
    container_name: node
    restart: always
    build:
      context: ./node
    depends_on:
      - db
    networks:
      - default-network
    volumes:
      - ./node:/app
      - /app/node_modules
  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password   

networks:
  default-network:
    driver: bridge
